# Generated by Django 3.2.4 on 2021-06-07 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('company_email', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'company_details',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('item_file', models.FileField(upload_to='')),
                ('item_long', models.FloatField()),
                ('item_lat', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_database.company')),
            ],
            options={
                'db_table': 'account_items',
            },
        ),
        migrations.CreateModel(
            name='UserCompanyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_database.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Company_User_Relationship',
            },
        ),
        migrations.CreateModel(
            name='SharedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_current', models.ForeignKey(db_column='company_current', on_delete=django.db.models.deletion.CASCADE, related_name='company_current', to='geo_database.company')),
                ('company_shared', models.ForeignKey(db_column='company_shared', on_delete=django.db.models.deletion.CASCADE, related_name='company_shared', to='geo_database.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_database.items')),
            ],
            options={
                'db_table': 'shared_files',
            },
        ),
        migrations.CreateModel(
            name='fileStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_file_size', models.CharField(max_length=200)),
                ('used_file_size', models.CharField(max_length=200)),
                ('remaining_file_size', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_database.company')),
            ],
            options={
                'db_table': 'file_storage',
            },
        ),
    ]
