# Generated by Django 3.2 on 2021-04-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
