# Generated by Django 3.2.4 on 2021-06-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_database', '0003_filestorage_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareditems',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usercompanyrelationship',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
