# Generated by Django 3.0.5 on 2021-06-01 08:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo_database', '0005_filestroage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fileStroage',
            new_name='fileStorage',
        ),
    ]
