# Generated by Django 3.0.5 on 2021-06-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_database', '0006_auto_20210601_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('company_email', models.CharField(max_length=200)),
                ('company_type', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'company_details',
            },
        ),
        migrations.AddField(
            model_name='filestorage',
            name='company_id',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='filestorage',
            name='company_name',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
