# Generated by Django 3.0.5 on 2021-06-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_database', '0007_auto_20210603_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filestorage',
            name='user',
        ),
    ]
